apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: ghcr.io/yichikawa/seweb-mysql:latest
          name: mysql8
          envFrom:
            - configMapRef:
                name: seweb-config
      imagePullSecrets:
        - name: ghcr
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql8
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
